#### 矩阵

+ 定义矩阵
+ 矩阵乘法

In [25]:
import numpy as np

A = np.array([[5,6],[9,10],[7,8]])
B = np.array([[5,6,7,8],[1,2,3,4]])
C = np.matmul(A,B)

print("A:\n", A)
print("B:\n", B)
print("\nA*B:\n", C)

A:
 [[ 5  6]
 [ 9 10]
 [ 7  8]]
B:
 [[5 6 7 8]
 [1 2 3 4]]

A*B:
 [[ 31  42  53  64]
 [ 55  74  93 112]
 [ 43  58  73  88]]


**矩阵操作**

+ 取矩阵的一行
+ 取矩阵的一列
+ 取矩阵的一部分

In [28]:
C_row = C[1,:]
C_col = C[:,2]
C_part = C[1:3,1:]
C_part02 = C[:,[0,2]]

print("C:\n", C)
print("\nRow 1 of C:\n", C_row)
print("Column 2 of C:\n", C_col)
print("Part of C:\n", C_part)
print("Column 0&2 of C:\n", C_part02)

C:
 [[ 31  42  53  64]
 [ 55  74  93 112]
 [ 43  58  73  88]]

Row 1 of C:
 [ 55  74  93 112]
Column 2 of C:
 [53 93 73]
Part of C:
 [[ 74  93 112]
 [ 58  73  88]]
Column 0&2 of C:
 [[31 53]
 [55 93]
 [43 73]]


**矩阵操作**
+ 矩阵添加一列
+ 矩阵按行求和
+ 矩阵按列求和

In [27]:
C_expand = np.concatenate([C,np.ones([3,1],dtype=int)],axis=1)

print("C:\n", C)
print("Expanded C:\n", C_expand)
print("\nSum of Rows:", C.sum(axis=1))
print("Sum of Columns:", C.sum(axis=0))

C:
 [[ 31  42  53  64]
 [ 55  74  93 112]
 [ 43  58  73  88]]
Expanded C:
 [[ 31  42  53  64   1]
 [ 55  74  93 112   1]
 [ 43  58  73  88   1]]

Sum of Rows: [190 334 262]
Sum of Columns: [129 174 219 264]
