### Diabetes数据分类

**预测某人是否患有糖尿病**
+ 数据文件：Diabetes.csv
+ 属性
    - $x_1$：怀孕次数 pregnancies
    - $x_2$：血浆葡萄糖浓度 plasma glucose concentration
    - $x_3$：舒张压 diastolic blood pressure
    - $x_4$：三头肌皮下脂肪 triceps skinfold thickness
    - $x_5$：胰岛素水平 insulin
    - $x_6$：体重指数 body mass index
    - $x_7$：糖尿病家族遗传因素 diabetes pedigree function
    - $x_8$：年龄 age
+ 预测输出$y$：是否患有糖尿病 diabetic

In [6]:
import numpy as np
import pandas as pd

data = pd.read_csv("Diabetes.csv")

X = data.iloc[:,0:8].to_numpy()
y = data.iloc[:,8].to_numpy()

print("X:",X.shape)
print(X[0:4,:])

print("\ny:",y.shape)
print(y[1:100])

X: (768, 8)
[[6.00e+00 1.48e+02 7.20e+01 3.50e+01 0.00e+00 3.36e+01 6.27e-01 5.00e+01]
 [1.00e+00 8.50e+01 6.60e+01 2.90e+01 0.00e+00 2.66e+01 3.51e-01 3.10e+01]
 [8.00e+00 1.83e+02 6.40e+01 0.00e+00 0.00e+00 2.33e+01 6.72e-01 3.20e+01]
 [1.00e+00 8.90e+01 6.60e+01 2.30e+01 9.40e+01 2.81e+01 1.67e-01 2.10e+01]]

y: (768,)
[0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1
 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1]


#### Logistic Regression分类预测

**分类正确率**
$$ \text{分类正确率} = \frac{\text{正确分类样本数}}{\text{总样本数}} $$

In [12]:
from sklearn.linear_model import LogisticRegression

CLF = LogisticRegression().fit(X, y)
predict_y = CLF.predict(X)

print("y == predict_y:")
print((y==predict_y)[0:100])

print("Accuate rate:", CLF.score(X,y))

y == predict_y:
[ True  True  True  True  True  True False False  True False  True  True
 False  True  True False False False  True False  True  True  True False
  True False  True  True False  True  True  True  True  True  True  True
 False False False  True False False  True  True False  True  True  True
 False  True  True  True  True  True False  True  True  True False  True
  True  True  True  True False  True False  True  True  True False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False  True  True
  True  True  True False]
Accuate rate: 0.7825520833333334


c:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
